# Generated by Django 5.1.1 on 2024-11-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='storage',
            field=models.FileField(blank=True, null=True, upload_to='movie/videos/'),
        ),
    ]
